version: "3"
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  web:
    image: sign2communicate-server
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      DB_HOST: localhost
      REDIS_HOST: redis
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "app.js"]
networks:
  webnet: